### ISSUE TITLE
希望后续加入一个右侧大纲也会跟着加粗走的这个操作

### ISSUE THREAD

**Issue by Joackk** [SiriusXT/trilium-show-position-in-toc#1]
感谢大佬的插件，试了下，很好用

就是现在大纲只是一直停留在看的那部分，比如我大纲比较多，需要滚动向下才能看到后续的大纲，加粗操作时候他会加粗，但如果遇到需要滚动的大纲，就看不到了，希望大佬后续可以加入这个功能

**Comment by SiriusXT** [comment]
改好了

**Comment by Joackk** [comment]
> 改好了

wc，大佬nb，这也太快了
