### ISSUE TITLE
判断点限制一下

### ISSUE THREAD

**Issue by Joackk** [SiriusXT/trilium-show-position-in-toc#2]
现在的话，似乎是全屏判定，也就是我想单独点大纲里的某个点时候，他不会判定，而是继续判定屏幕中的点，比如这里
我光标横向在加粗的这部分内容里，但是其实我鼠标这时候在我标记的这个位置，这里试了下，是可以点的，只是没有加粗，一开始我还以为点了没反应呢-  - 
![image](https://user-images.githubusercontent.com/45162558/225177909-1e4cd167-b384-4a9b-aada-54bc3f99cb6a.png)
后续可以加个判断限制吗？将其限制在文章这部分里，大纲这部分不包含在其中

**Comment by SiriusXT** [comment]
改好了

**Comment by Joackk** [comment]
> 改好了

666
